### ISSUE TITLE
No licence for repo

### ISSUE THREAD

**Issue by nmerget** [why-try313/godot-ECMAScript-cookbook#1]
@why-try313 

I would love to use the [images](https://github.com/why-try313/godot-ECMAScript-cookbook/tree/master/wiki-images) inside https://github.com/Geequlim/ECMAScript, but there is no licence here.

I won't be able to copy them, if I'm not allowed to.

**Comment by whytry313** [comment]
@nmerget Sure! I'll set it to MIT, however please note that they don't work that well on dark mode
